{% set name = "dcw-gmt" %}
{% set version = "1.1.4" %}
{% set sha256 = "8d47402abcd7f54a0f711365cd022e4eaea7da324edac83611ca035ea443aad3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: ftp://ftp.soest.hawaii.edu/dcw/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

test:
  commands:
    - test -f $PREFIX/share/{{ name }}/LICENSE.TXT                             # [unix]
    - test -f $PREFIX/share/{{ name }}/{{ name }}.nc                           # [unix]
    - if not exist %PREFIX%\\Library\\share\\{{ name }}\\LICENSE.TXT exit 1    # [win]
    - if not exist %PREFIX%\\Library\\share\\{{ name }}\\{{ name }}.nc exit 1  # [win]

about:
  home: http://www.soest.hawaii.edu/wessel/dcw/
  license: LGPL
  license_family: GPL
  license_file: LICENSE.TXT
  summary: 'DCW-GMT - The Digital Chart of the World for GMT 5'

  description: |
    The Digital Chart of the World (DCW) is a comprehensive
    1:1,000,000 scale vector basemap of the world. The charts were
    designed to meet the needs of pilots and air crews in medium-and
    low-altitude en route navigation and to support military
    operational planning, intelligence briefings, and other
    needs. This is the version of DCW used by Generic Mapping Tools.
  doc_url: http://www.soest.hawaii.edu/wessel/dcw/
  dev_url: http://www.soest.hawaii.edu/wessel/dcw/

extra:
  recipe-maintainers:
    - mhearne-usgs
    - leouieda
