{% set name = "dcw-gmt" %}
{% set version = "2.1.2" %}
{% set sha256 = "4bb840d075c8ba3e14aeb41cf17c24236bff787566314f9ff758ab9977745d99" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/GenericMappingTools/dcw-gmt/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

test:
  commands:
    - test -f $PREFIX/share/{{ name }}/LICENSE                                 # [unix]
    - test -f $PREFIX/share/{{ name }}/{{ name }}.nc                           # [unix]
    - if not exist %PREFIX%\\Library\\share\\{{ name }}\\LICENSE exit 1        # [win]
    - if not exist %PREFIX%\\Library\\share\\{{ name }}\\{{ name }}.nc exit 1  # [win]

about:
  home: http://www.soest.hawaii.edu/wessel/dcw/
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'DCW-GMT - The Digital Chart of the World for GMT'

  description: |
    The Digital Chart of the World (DCW) is a comprehensive
    1:1,000,000 scale vector basemap of the world. The charts were
    designed to meet the needs of pilots and air crews in medium-and
    low-altitude en route navigation and to support military
    operational planning, intelligence briefings, and other
    needs. This is the version of DCW used by Generic Mapping Tools.
  doc_url: http://www.soest.hawaii.edu/wessel/dcw/
  dev_url: http://www.soest.hawaii.edu/wessel/dcw/

extra:
  recipe-maintainers:
    - mhearne-usgs
    - leouieda
    - seisman
