{% set name = "dcw-gmt" %}
{% set version = "2.0.1" %}
{% set sha256 = "5c90b2968f4095cf5ea44a354dc9d8f9dd1b8fe5514e0338ff85b48e03547a25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: ftp://ftp.soest.hawaii.edu/dcw/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

test:
  commands:
    - test -f $PREFIX/share/{{ name }}/LICENSE                                 # [unix]
    - test -f $PREFIX/share/{{ name }}/{{ name }}.nc                           # [unix]
    - if not exist %PREFIX%\\Library\\share\\{{ name }}\\LICENSE exit 1        # [win]
    - if not exist %PREFIX%\\Library\\share\\{{ name }}\\{{ name }}.nc exit 1  # [win]

about:
  home: http://www.soest.hawaii.edu/wessel/dcw/
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'DCW-GMT - The Digital Chart of the World for GMT 5'

  description: |
    The Digital Chart of the World (DCW) is a comprehensive
    1:1,000,000 scale vector basemap of the world. The charts were
    designed to meet the needs of pilots and air crews in medium-and
    low-altitude en route navigation and to support military
    operational planning, intelligence briefings, and other
    needs. This is the version of DCW used by Generic Mapping Tools.
  doc_url: http://www.soest.hawaii.edu/wessel/dcw/
  dev_url: http://www.soest.hawaii.edu/wessel/dcw/

extra:
  recipe-maintainers:
    - mhearne-usgs
    - leouieda
    - seisman
