travis:
  secure:
    BINSTAR_TOKEN: g1JoBnpLht52qR0FzBQWJ4s+2uYvlIVYqftP2QHciqOuZNtbnCAnWY//f7khe0CyTtiRiUihrZAYyHj16aippsUItdYtAPlEs5IBTsV95bQPVYJu+5SQIMJQSwgrxZvngpH+1c/r/r/94uwHKQKsOmZ2tH7KkzO+A+Ltg1DwsQKefQeC3m4xTJIbTI7Vh5ichFZbUlMZgziramXAWvrwpSfrJH+7cFnkqwbNFAaMPcL1Rrc7oepdBkGKq+A+tfH0xgLq/5K2x6/WOPXN9XdBjo8MtI8KQfnNSubosyma24FvFAfzhPymhUbuf+RgKSnuenGwzOgeIkzj9StYUmSGCHz/D2Qlv/rNy+oxVYwttPWZw6gka70zWQ2Gxebgwdz1iME2EugTQxGFCNGNh9txx63IqbVriErLadNoXYk4tHkzOW02kWD4JF+mcsy/aTtaJbkAi31VKcqeJC5kX8Ui8n0QYwsrZH5x/sosEVocaKzTy7KXBdZAK7MgsNbL4wzgYSMovloeBy/c2tkHRM2bsR+jBunGOxYbDYb5swukWJ/8zEO8p9zgvK16lzJ/Z0sJJbDzcxBPnePnjElEason1yMR13sPyUrbyEA7mrSCNLLFY5NEPSRf8HJyICvgZQz3vgewkxsfay1AlPM0h5EZ1m6hlD6+ERDsoMC4XdZpxUE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
