travis:
  secure:
    BINSTAR_TOKEN: Cd3rnLms93bWjg2q4Jo6QIGVy4Bhe8ZXiQi52e8RNbeEJBaFcQF8tAY5tRW4ktjkWXLJtn7+ty7M9/SB6Y8Y/CUoRVRMr4BHRX/3Ss8M5Q9SMFr4hmNhmLDiJqmXEbDyt4lr5LD88UAq8UKTdR31t3dTpGGaXWaMWMBzu+YisK2e+Z4y8ozlMlpdJyRH4UnGrOE+TRrZegkByciuvpvBmymFSEM3r/YyDRCEThdMVGJ/YhkSwtfDr+p96asfU+Hq1wGtbSucc17VCJ0cNk8XFNo4z98oROWSMeI3WZqiFREsaepPI06Hjc5lEaYNp4/VfrgsXAsYd+AplQml9HVsnGDDpWfKbvhejyaUT/+vNysBJpniZ2MKyEL1xixLEvRHjI0v6aYRgTQFqN7cS85Bs7hzMVDP+cxzUsywSP7ZPH6VozgAcYYCeeGkoeENwjbILwSV63Jj0J8x2d0fPrEGzCQZAGqckH6g4Vi1tIxyNcmUR461c6newDvyhM+5fWUSyy/RCynMdZ43BLPFgbFVE0KHpdAlLqZ0nfvmkAaW70YKrErobvOiwyuvgvOZWSP5cFZ0jpqcGdO6GRcq+cIkcrNNmnfgvZYWUvhVgVIEInvAKxLxZtu9qx11skXSNup/4y1PmR6AePsVClPRT79VhQIypTbB4yeYYQ0F5LKAn1Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider:
  win: azure
